Add release notes plugin
wooga/atlas-plugins pull request #34
Opened 2021-05-06 14:47 UTC by Joaquimmnetto

Before open a new pull request please check the following list.

_You don't need to add this checklist to the pull request body._
- [ ] add new tests to test your changes
- [ ] run the tests and check that they pass
- [ ] cleanup your commits
- [ ] write good pull request description
- [ ] add appropiate labels

## Description
Added the github-release-notes plugin to generate more meaningful release notes. These notes will be based in the included PRs `##Changes` section, and in lack of these, it will use the PRs names. There are references to the user which submited the PR and for the PR that generated these changes  

Bellow, a sample of how the release notes will be formatted (in markdown):

```markdown
 ## Changes
    
* ![ADD] new test feature [[#2](https://github.com/test/issue/2)] [@TestUser](https://github.com/TestUser)
* ![ADD] test suite startup [[#1](https://github.com/test/issue/1)] [@TestUser](https://github.com/TestUser)
* ![FIX] test suite startup [[#2](https://github.com/test/issue/2)] [@TestUser](https://github.com/TestUser)
* ![FIX] test suite tools [[#2](https://github.com/test/issue/2)] [@TestUser](https://github.com/TestUser)
* ![FIX] runner test setup code [[#1](https://github.com/test/issue/1)] [@TestUser](https://github.com/TestUser)
* ![IMPROVE] test suite [[#2](https://github.com/test/issue/2)] [@TestUser](https://github.com/TestUser)

[ADD]: https://resources.atlas.wooga.com/icons/icon_add.svg
[FIX]: https://resources.atlas.wooga.com/icons/icon_fix.svg
[IMPROVE]: https://resources.atlas.wooga.com/icons/icon_improve.svg
```

## Changes
* ![ADD] add release notes plugin

[NEW]:https://atlas-resources.wooga.com/icons/icon_new.svg "New"
[ADD]:https://atlas-resources.wooga.com/icons/icon_add.svg "Add"
[IMPROVE]:https://atlas-resources.wooga.com/icons/icon_improve.svg "IMPROVE"
[CHANGE]:https://atlas-resources.wooga.com/icons/icon_change.svg "Change"
[FIX]:https://atlas-resources.wooga.com/icons/icon_fix.svg "Fix"
[UPDATE]:https://atlas-resources.wooga.com/icons/icon_update.svg "Update"

[BREAK]:https://atlas-resources.wooga.com/icons/icon_break.svg "Remove"
[REMOVE]:https://atlas-resources.wooga.com/icons/icon_remove.svg "Remove"
[IOS]:https://atlas-resources.wooga.com/icons/icon_iOS.svg "iOS"
[ANDROID]:https://atlas-resources.wooga.com/icons/icon_android.svg "Android"
[WEBGL]:https://atlas-resources.wooga.com/icons/icon_webGL.svg "WebGL"
[UNITY]:https://atlas-resources.wooga.com/icons/icon_unity.svg "Unity"
[GRADLE]:https://atlas-resources.wooga.com/icons/icon_gradle.svg "Gradle"
[LINUX]:https://atlas-resources.wooga.com/icons/icon_linux.svg "Linux"

2021-05-11 18:49 UTC, Larusso requested changes
Just some smaller adjustments.
It already worked on linux and macOS. I don't know why the windows build stalled. Lets kick it again after you did the last small changes.

2021-05-11 18:49 UTC, Larusso commented on src/main/groovy/wooga/gradle/plugins/PluginsPlugin.groovy
> +        GithubPublish githubPublishTask = (GithubPublish) tasks.getByName(GithubPublishPlugin.PUBLISH_TASK_NAME) //check
Which cast do you prefer :)
One throws the other looks nicer.

2021-05-12 10:31 UTC, Joaquimmnetto commented on src/main/groovy/wooga/gradle/plugins/PluginsPlugin.groovy
> +        GithubPublish githubPublishTask = (GithubPublish) tasks.getByName(GithubPublishPlugin.PUBLISH_TASK_NAME) //check
In this case both should be the "java" checked cast, because we need the objects actual attributes. But usually I prefer the 'as' cast, as it is nicer, as you said :)

2021-05-12 10:38 UTC, Joaquimmnetto commented on src/main/groovy/wooga/gradle/plugins/releasenotes/ChangeSet.groovy
> +class ChangeSet<B extends com.wooga.github.changelog.changeSet.ChangeSet<GHCommit, GHPullRequest>> implements com.wooga.github.changelog.changeSet.ChangeSet, Logs<GHCommit>, PullRequests<GHPullReques
We do need it, as it shares name with the current class, so every "ChangeSet" reference would point to it.

2021-05-12 10:47 UTC, Larusso commented on src/main/groovy/wooga/gradle/plugins/releasenotes/ChangeSet.groovy
> +class ChangeSet<B extends com.wooga.github.changelog.changeSet.ChangeSet<GHCommit, GHPullRequest>> implements com.wooga.github.changelog.changeSet.ChangeSet, Logs<GHCommit>, PullRequests<GHPullReques
Ah ok my bad

2021-05-12 12:24 UTC, Larusso approved these changes

2021-05-12 17:10 UTC, merged